### PR TITLE
Implement Movable items

### PR DESCRIPTION
**Pull request by Integr-0**
Removed styling in App.css (because styling happend in movableItem)
Cleaned Up old movable item code from App.tsx
updated mousetracker to return target
added MoveableItem.tsx and Finished movable item code (also moved old code into this file)

image

Movable items only show debug info Currently
Needs to be changed in the future (i (Erik) can do that)

Moving item Example:
image

> Fixed a Bug where you can carry multiple items
> Fixed a Bug where you cant move items up or left
> Fixed a Bug where you Would Crash the Website (too many event listeners.... 😁)
> FIxed a Bug where you couldnt stop carrying an Item

### CODE REVIEW

**Comment by Integr-0** [comment]
Styles and Text for the Element will be modified and added in the future, and meanwhile replaced with debug info (for debugging.... :) )

**Comment by Integr-0** [comment]
@Julian-Mostbauer Please Review

**Comment by Integr-0** [comment]
Added Custom Styling and Elements 
image

**Review by Integr-0 — COMMENTED** [review]
Looks ok

**Comment by Julian-Mostbauer** [comment]
Ander professionell einfach

**Pull request merged**
